🚧 Implementa módulo Product
elioenays/cardapio pull request #19
Opened 2023-05-10 18:15 UTC by JLPimenta

2023-05-10 20:26 UTC, elioenays commented
@JLPimenta quando for mexer no projeto, da um git fetch, subi a atualização do banco e atualizei a seed pra criar umas mesas

2023-05-11 12:02 UTC, elioenays requested changes
Módulo está funcionando, porém precisa fazer as correções e trativas de erros.

- [ ] Validar o ingredientId da requisição com class Validator definindo um array de objetos com as propriedades de criação do ingrediente (comentei um exemplo de solução)
- [ ] remover `@UsePipes(new ValidationPipe())` do controller, isso só é necessário quando você precisa utilizar configurações de validação diferente das configurações globais definidas no main
- [ ]  Validar se o categoryId existe, para evitar erros desconhecidos no servidor
- [ ] Validar se o ingredientId existe, para evitar erros desconhecidos no servidor

2023-05-11 17:20 UTC, JLPimenta commented on backend/src/modules/product/product.controller.ts
> +  @UsePipes(new ValidationPipe())
Anotação ```@UsePipes(new ValidationPipe())``` removida, aguardar novo push.

2023-05-11 18:45 UTC, JLPimenta commented on backend/src/modules/product/use-cases/createProduct.ts
Validações implementadas como ``` validateCreateProductUseCase() ```, conforme feedbacks do code review

2023-05-11 18:46 UTC, JLPimenta commented on backend/src/modules/product/dto/create-product-dto.ts
Implementado conforme feedback de code review. Aguardar novo push.

2023-05-11 20:49 UTC, elioenays requested changes
A funcionalidade foi testada e está funcionando

Só considerar essas alterações

- [ ] a quantidade do ingrediente deve ser opcional, se não for passado, o padrão será 1 (definido no banco de dados)
- [ ] alterar `ConflictException `para `NotFoundException`

2023-05-11 20:49 UTC, elioenays commented on backend/src/modules/product/factory/validateCreateProductUseCase.ts
> +      throw new ConflictException('Ingredient not found.');
para exceções de dados não encontrados utilizamos o `NotFoundException`

2023-05-11 20:56 UTC, elioenays requested changes

2023-05-11 20:56 UTC, elioenays commented on backend/src/modules/product/factory/validateCreateProductUseCase.ts
> +  category,
Tipar esses parametros

```javascript
  ingredients: IngredientsParams[],
  product: Product,
  category: Category,
```

2023-05-11 21:30 UTC, JLPimenta commented
Correções e sugestões implementadas, aguardando aprovação do code reviewer.

2023-05-12 00:50 UTC, elioenays approved these changes
correções aplicadas

2023-05-12 00:50 UTC, merged